"""Unit tests for the post-inference semantic XML extraction and parsing layer.

Validates that structural formatting, token boundaries, and language tags are
isolated correctly from remote inference wrappers or fallback payloads.
"""

import pytest

from src.guardrails.guardrails import (
    ClinicalGuardrailException,
    NeonatalOutputGuardrail,
)


def extract_tag_flexible_mock(text: str, tag_name: str) -> str:
    """Mock implementation mirroring app.py's exact internal parsing logic.

    Ensures regular expression substitutions and character casing configurations
    are tested in structural isolation.
    """
    tag_lower = tag_name.lower()
    start_tag = f"<{tag_lower}>"
    end_tag = f"</{tag_lower}>"

    # Normalize uppercase/lowercase XML tags generated by the LLM wrapper
    text_norm = text.replace(f"<{tag_name.upper()}>", start_tag).replace(
        f"</{tag_name.upper()}>", end_tag
    )

    if start_tag in text_norm:
        parts = text_norm.split(start_tag)
        if len(parts) > 1:
            content_part = parts[1]
            if end_tag in content_part:
                return content_part.split(end_tag)[0].strip()
            return content_part.strip()
    return ""


def test_parser_extracts_correct_casing() -> None:
    """Verifies that lowercase XML boundary enclosures are isolated cleanly."""
    llm_payload = (
        "<raport>The neonate shows stable telemetry parameters.</raport>"
        "<medicatie>Maintain standard baseline intervals.</medicatie>"
    )

    extracted_raport = extract_tag_flexible_mock(llm_payload, "RAPORT")
    extracted_med = extract_tag_flexible_mock(llm_payload, "MEDICATIE")

    assert extracted_raport == "The neonate shows stable telemetry parameters."
    assert extracted_med == "Maintain standard baseline intervals."


def test_parser_extracts_uppercase_casing() -> None:
    """Verifies that uppercase XML tags are normalized and parsed without truncation."""
    llm_payload = (
        "<RAPORT>Analiza clinica arata parametri fiziologici stabili.</RAPORT>"
        "<FCC>Protocoale FCC active in incubator.</FCC>"
    )

    extracted_raport = extract_tag_flexible_mock(llm_payload, "raport")
    extracted_fcc = extract_tag_flexible_mock(llm_payload, "fcc")

    assert extracted_raport == "Analiza clinica arata parametri fiziologici stabili."
    assert extracted_fcc == "Protocoale FCC active in incubator."


def test_parser_returns_empty_on_missing_boundaries() -> None:
    """Guarantees that raw unstructured strings return an empty fallback to prevent crashes."""
    unstructured_payload = (
        "The model failed to encapsulate this content within XML tokens."
    )

    extracted_raport = extract_tag_flexible_mock(unstructured_payload, "RAPORT")
    assert extracted_raport == ""


# ======================================================================================================================
# 🛡️ EXPANSION LAYER: CLINICAL GUARDRAIL VALIDATION TESTS
# ======================================================================================================================


def test_guardrail_accepts_valid_clinical_report() -> None:
    """Verifies that a fully compliant XML payload passes guardrail validation successfully."""
    guardrail = NeonatalOutputGuardrail()
    valid_payload = (
        "<RAPORT>\nPatient is stable. No signs of advanced systemic shock.\n</RAPORT>\n"
        "<MEDICATIE>\nAdminister Ampicillin 250 mg IV on q12h schedule.\n</MEDICATIE>\n"
        "<FCC>\nKangaroo care active for 60 minutes inside the stable incubator environment.\n</FCC>"
    )

    # Fixed: Unpacking the new tuple return format (success, cleaned_output)
    success, cleaned_output = guardrail.validate_structure(valid_payload)
    assert success is True
    assert "<RAPORT>" in cleaned_output
    assert guardrail.validate_clinical_safety(valid_payload, weight_kg=2.50) is True


def test_guardrail_self_heals_missing_fcc_tag() -> None:
    """Verifies that the guardrail successfully injects the fallback FCC block if omitted by the LLM."""
    guardrail = NeonatalOutputGuardrail()
    incomplete_payload = (
        "<RAPORT>\nPatient is recovering nicely under monitoring.\n</RAPORT>\n"
        "<MEDICATIE>\nAdminister basic fluids 20 ml.\n</MEDICATIE>"
    )

    success, cleaned_output = guardrail.validate_structure(incomplete_payload)
    assert success is True
    assert "<FCC>" in cleaned_output.upper()  # Confirms self-healing injected the block
    assert "Family-Centered Care" in cleaned_output


def test_guardrail_raises_exception_on_broken_xml_structure() -> None:
    """Verifies that an unclosed or missing structural partition tag triggers a strict structure exception."""
    guardrail = NeonatalOutputGuardrail()
    corrupt_payload = (
        "<RAPORT>\nPatient data is visible.\n</RAPORT>\n"
        "<MEDICATIE>\nAdminister Ampicillin 250 mg IV.\n"  # Missing </MEDICATIE> closing tag
        "<FCC>\nSoundstage mitigation active.\n</FCC>"
    )

    with pytest.raises(ClinicalGuardrailException, match="Critical structure failure"):
        guardrail.validate_structure(corrupt_payload)


def test_guardrail_intercepts_absolute_ceiling_dosage_breach() -> None:
    """Guarantees the guardrail blocks dosages exceeding the absolute maximum neonatal threshold (>500mg)."""
    guardrail = NeonatalOutputGuardrail()
    dangerous_payload = (
        "<RAPORT>\nHigh risk patient diagnostics active.\n</RAPORT>\n"
        "<MEDICATIE>\nAdminister generic compound 750 mg immediately via IV drip.\n</MEDICATIE>\n"
        "<FCC>\nMaintain low ambient noise.\n</FCC>"
    )

    with pytest.raises(
        ClinicalGuardrailException, match="exceeds absolute neonatal ceiling"
    ):
        guardrail.validate_clinical_safety(dangerous_payload, weight_kg=2.50)


def test_guardrail_intercepts_weight_relative_dosage_breach() -> None:
    """Guarantees the guardrail intercepts a high dosage relative to an extremely low neonatal weight."""
    guardrail = NeonatalOutputGuardrail()
    # 200 mg is below the 500mg absolute ceiling, but for a 1.0 kg premature baby,
    # it represents 200 mg/kg, which violates our smart 150 mg/kg threshold.
    dangerous_payload = (
        "<RAPORT>\nPremature infant shows early systemic distress markers.\n</RAPORT>\n"
        "<MEDICATIE>\nAdminister high dose aggressive baseline 200mg IV loop.\n</MEDICATIE>\n"
        "<FCC>\nMinimize infant handling cycles.\n</FCC>"
    )

    with pytest.raises(ClinicalGuardrailException, match="critically high"):
        guardrail.validate_clinical_safety(dangerous_payload, weight_kg=1.00)
